### ISSUE TITLE
 404 Not Found: @radial-color-picker/angular-color-picker@latest

### ISSUE THREAD

**Issue by MikhaelGerbet** [radial-color-picker/angular-color-picker#1]

**Comment by GusSL** [comment]
Same. :(

**Comment by mitch85** [comment]
dito :(

**Comment by jvv** [comment]
Yeah.. same. If you do want to use this already before it's actually available on npmjs you can:

- clone repo
- install repo
- npm run build_lib
- tar the folder in the /dist created through the build_lib command
- npm install ./the_tar_file.tgz

and play around with it.

**Comment by talamaska** [comment]
yeah, sorry it still not published

**Comment by talamaska** [comment]
@MikhaelGerbet @GusSL @mitch85 @jvv @IndustrialShields 
I waited for angular 9. 
Finally it's published to npm after 2 years of wait. 
I was busy with other stuff and finally had time to finalize the library and make a publish.
Please try it and report any issues you find.
